### PR TITLE
fix(iam): Don't leak constants

### LINKED ISSUE #22: IAMTokenManager leaks constants names
Hi everyone,

I was experiencing some unusual behaviour on a project where, by simply adding the `ibm-watson` gem to the `Gemfile` I would get several requests to fail with a `400 Bad request` error message.

Digging through the code I found out that [IAMTokenManager is declaring constants outside the class scope](https://github.com/watson-developer-cloud/ruby-sdk/blob/master/lib/ibm_watson/iam_token_manager.rb#L8-L14), so they are being leaked to the rest of the application.

This was causing issues for me because [Faraday uses the value of `CONTENT_TYPE` as the header key](https://github.com/lostisland/faraday/blob/master/lib/faraday/request/url_encoded.rb#L3), so my requests were sending a ill-formed ` Application/x-Www-Form-Urlencoded: application/x-www-form-urlencoded` header.

The fix should be simple enough, since I don't think these values are referenced outside this class.

### PR DESCRIPTION
**Pull request by lgfa29**
The IAMTokenManager class declared its constants outside the class
definition, which caused undesired side-effect on pieces of code that
also relied on these contants names.

Fixes #22

### CODE REVIEW

**Comment by lgfa29** [comment]
Hum....not sure how to fix the errors in the integration tests.

**Comment by maxnussbaum** [comment]
@lgfa29 I'll be opening a PR soon that should hopefully address the issue that is causing the tests to fail.

**Comment by mamoonraja** [comment]
@lgfa29 PR looks good, looks like you need to sign the CLA before we can merge.

**Comment by lgfa29** [comment]
@mamoonraja sure, where can I find the CLA?

**Comment by mediumTaj** [comment]
Badge is in another PR but here is the CLA link 

https://cla-assistant.io/watson-developer-cloud/ruby-sdk

**Comment by lgfa29** [comment]
Thanks @mediumTaj. Signed 📝

**Pull request merged**
